### ISSUE TITLE
Support ; in selection

### ISSUE THREAD

**Issue by mrleblanc101** [weareindi/atom--var-that-color#4]
Hi,
Shouldn't the plugin support ; in selection ?
If there is, nothing happen, not even an error message.

**Comment by weareindi** [comment]
All sorted. Thanks for reporting.
This is fixed in 0.2.3

Any other issues - let us know.

**Comment by mrleblanc101** [comment]
Nice, thanks !
Two years since last version so I wasn't sure if I would get a response, especially not that quickly !
