### ISSUE TITLE
Use cursor scope instead of extension for conversion

### ISSUE THREAD

**Issue by mrleblanc101** [weareindi/atom--var-that-color#6]
Hi,
Me again 😅 

The plugin seems to determine the output from the file extension, which is a problem when the file is unsaved as it has no extension because it's unsaved. You should use the current cursor scope. 

For exemple, an unsaved file can have a LESS scope, but the generated variable are not LESS compatible (seems like a general fallback). 

Also this would be great for Vue single file component file as their extension is .vue but you can use any pre-processor in them (atom already set the correct scope from the lang attribute on the style tag)

**Comment by weareindi** [comment]
Just uploaded 0.4.0 with this addition.
Please test it out and let us know of any issues.

Thanks for all the input recently @mrleblanc101 . It's great!

**Comment by mrleblanc101** [comment]
I just need to check Vue file, but so far so good
