### ISSUE TITLE
Missing CSS custom proprieties and Stylus support 

### ISSUE THREAD

**Issue by mrleblanc101** [weareindi/atom--var-that-color#7]
Hi,
Me again 😅 
The plugin seems to be missing CSS Custom Propriety (--color-cerise: #d33682) support and Stylus variables (color-cerise = #d33682)

**Comment by weareindi** [comment]
Just uploaded 0.4.0 with this addition.
Please test it out and let us know of any issues.

**Comment by mrleblanc101** [comment]
It think I'll just open issue for random github project here since you are so efficient 😅
Thanks, seems to works fine
